export const personalities = [
  { name: "Friendly" },
  { name: "Shy" },
  { name: "Energetic" },
  { name: "Calm" },
  { name: "Independent" },
  { name: "Affectionate" },
  { name: "Curious" },
  { name: "Lazy" },
  { name: "Fearless" },
  { name: "Timid" },
  { name: "Outgoing" },
  { name: "Reserved" },
  { name: "Adventurous" },
  { name: "Relaxed" },
  { name: "Playful" },
  { name: "Serious" },
  { name: "Loyal" },
  { name: "Sociable" },
  { name: "Aggressive" },
  { name: "Gentle" },
];
